# Generated by Django 3.0.8 on 2020-12-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='images/products/')),
                ('Product_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product_origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_code', models.CharField(max_length=15)),
                ('Product_name', models.CharField(max_length=30)),
                ('Product_mrp', models.IntegerField()),
                ('Product_salepercentage', models.IntegerField()),
                ('Product_saleprice', models.IntegerField()),
                ('Product_UOF', models.CharField(max_length=50)),
                ('Product_availability', models.BooleanField(default=False)),
                ('Product_company', models.CharField(max_length=50)),
                ('Product_extranote', models.CharField(max_length=5)),
                ('Product_regestrationtime', models.TimeField(auto_now=True)),
            ],
        ),
    ]
