# Generated by Django 3.0.8 on 2020-12-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_auto_20201205_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_origin',
            name='Product_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
