# Generated by Django 3.0.8 on 2020-12-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0004_auto_20201205_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_origin',
            name='Product_extranote',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product_origin',
            name='Product_salepercentage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_origin',
            name='Product_saleprice',
            field=models.IntegerField(blank=True),
        ),
    ]
