# Generated by Django 3.0.8 on 2020-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20201110_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('coverimage', models.ImageField(upload_to='images/user/covers')),
            ],
        ),
    ]
