# Generated by Django 3.0.8 on 2020-11-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_acess_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlinkauthid', models.IntegerField()),
                ('userid', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
