# Generated by Django 3.0.8 on 2020-11-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_acess_info',
            name='hasuploded',
            field=models.BooleanField(default=False),
        ),
    ]
