# Generated by Django 3.0.8 on 2020-11-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userv1', '0002_user_acess_info_hasuploded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_acess_info',
            name='hasuploded',
        ),
    ]
